// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMS.Infrastructure.Persistence;

#nullable disable

namespace SMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    [Migration("20260108143257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Aggregates.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("engagements", (string)null);
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.BillableService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("billable_services", (string)null);
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.EngagementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("engagement_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("engagement_id", "ServiceId")
                        .IsUnique();

                    b.ToTable("engagement_lines", (string)null);
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.Tranche", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("engagement_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("engagement_id");

                    b.ToTable("tranches", (string)null);
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Aggregates.Engagement", b =>
                {
                    b.OwnsOne("SMS.Domain.Modules.Finance.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("EngagementId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("total_currency");

                            b1.HasKey("EngagementId");

                            b1.ToTable("engagements");

                            b1.WithOwner()
                                .HasForeignKey("EngagementId");
                        });

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.BillableService", b =>
                {
                    b.OwnsOne("SMS.Domain.Modules.Finance.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("BillableServiceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("price_currency");

                            b1.HasKey("BillableServiceId");

                            b1.ToTable("billable_services");

                            b1.WithOwner()
                                .HasForeignKey("BillableServiceId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.EngagementLine", b =>
                {
                    b.HasOne("SMS.Domain.Modules.Finance.Aggregates.Engagement", null)
                        .WithMany("Lines")
                        .HasForeignKey("engagement_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SMS.Domain.Modules.Finance.ValueObjects.Money", "PriceSnapshot", b1 =>
                        {
                            b1.Property<Guid>("EngagementLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("price_currency");

                            b1.HasKey("EngagementLineId");

                            b1.ToTable("engagement_lines");

                            b1.WithOwner()
                                .HasForeignKey("EngagementLineId");
                        });

                    b.OwnsOne("SMS.Domain.Modules.Finance.ValueObjects.ServiceQuantity.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("EngagementLineId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("EngagementLineId");

                            b1.ToTable("engagement_lines");

                            b1.WithOwner()
                                .HasForeignKey("EngagementLineId");
                        });

                    b.Navigation("PriceSnapshot")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.Student", b =>
                {
                    b.OwnsOne("SMS.Domain.Modules.Finance.ValueObjects.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("StudentId");

                            b1.ToTable("students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("BirthDate")
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Entities.Tranche", b =>
                {
                    b.HasOne("SMS.Domain.Modules.Finance.Aggregates.Engagement", null)
                        .WithMany("Tranches")
                        .HasForeignKey("engagement_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SMS.Domain.Modules.Finance.ValueObjects.Money", "AmountDue", b1 =>
                        {
                            b1.Property<Guid>("TrancheId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("amount_due");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("currency");

                            b1.HasKey("TrancheId");

                            b1.ToTable("tranches");

                            b1.WithOwner()
                                .HasForeignKey("TrancheId");
                        });

                    b.Navigation("AmountDue")
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Domain.Modules.Finance.Aggregates.Engagement", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Tranches");
                });
#pragma warning restore 612, 618
        }
    }
}
